# Site Settings
title: "Lena Ulbricht"
description: "Political Scientist and Digital Policy Expert"
baseurl: "" # the subpath of your site, e.g. "/blog"
url: https://lena-ulbricht.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
repository: "lena-ulbricht/lena-ulbricht.github.io"

# Author Information
author:
  name: "Lena Ulbricht"
  pronouns         : "she/her"  
  bio: "Political Scientist and Digital Policy Expert"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed

#Permalink Structure
permalink: /:name/

#Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

#Encoding
encoding: "utf-8"